version: '3.8'

services:
  api-server:
    build: 
      context: ./api-nodeJS
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api-nodeJS:/app
    environment:
      - NODE_ENV=production
    restart: always

  discord-bot:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    depends_on:
      - api-server
    environment:
      - NODE_ENV=production
      - API_URL=http://api-server:3000
    restart: always
