version: '3.8'

services:
  api-server:
    build: 
      context: ./api-nodeJS
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./api-nodeJS:/app
    environment:
      - PORT=3333
      - NODE_ENV=production
      - TZ=Asia/Seoul
    restart: always

  discord-bot:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    depends_on:
      - api-server
    environment:
      - NODE_ENV=production
      - API_URL=http://api-server:3333
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - TZ=Asia/Seoul
    restart: always

  client:
    build:
      context: ./TMUB-client/web-vue
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./TMUB-client/web-vue:/app
      - /app/node_modules
    environment:
      - API_URL=http://api-server:3333
      - TZ=Asia/Seoul
    restart: always
