version: '3.8'

services:
  api-server:
    build: ./api-nodeJS
    ports:
      - "3000:3000"
    volumes:
      - ./api-nodeJS:/app
    environment:
      - NODE_ENV=production

  discord-bot:
    build: ./discord-bot
    depends_on:
      - api-server
    environment:
      - NODE_ENV=production
      - API_URL=http://api-server:3000
